'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'
'     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
'     程式碼，變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    ''' <summary>
    ''' SuccessMessagePlaceHolder 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' ChangePassword 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents ChangePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' CreatePassword 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents CreatePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' PhoneNumber 控制項。
    ''' </summary>
    ''' <remarks>
    ''' 自動產生的欄位。
    ''' 若要修改，請將欄位宣告從設計工具檔案移至程式碼後置檔案。
    ''' </remarks>
    Protected WithEvents PhoneNumber As Global.System.Web.UI.WebControls.Label
    
End Class
